#!/usr/bin/python3
def raise_exception_msg(message=""):
    """The finctio raise personal message"""
    raise NameError(message)
